language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
#before_install:
#  - chmod a+x ./test.sh
install:
  - echo "run pip here"
# - "pip install -r requirements.txt"
before_script:
  - pip install coverage
script:
  - pylint *.py
#  - "./test.sh"
#after_success:
#  - bash <(curl -s https://codecov.io/bash)
