language: python
python:
  - "3.5"
  - "3.6"
before_install:
  - python -m pip install --upgrade pip
  - pip --version
  - chmod a+x ./test.sh
install:
  - pip install -r requirements.txt
before_script:
  - pip install coverage pylint flake8
script:
  - pylint *.py && flake8 *.py
  - "./test.sh"
#after_success:
#  - bash <(curl -s https://codecov.io/bash)
